"""add organization member role

Revision ID: 735ad6fcbafa
Revises: c1629bcf8f68
Create Date: 2026-07-20 14:46:13.918503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735ad6fcbafa'
down_revision: Union[str, Sequence[str], None] = 'c1629bcf8f68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('role', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_members', 'role')
    # ### end Alembic commands ###
