"""add created_at to organization invitations

Revision ID: 9610eccce09b
Revises: e96d980ad73c
Create Date: 2026-07-29 11:38:56.253235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9610eccce09b'
down_revision: Union[str, Sequence[str], None] = 'e96d980ad73c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_invitations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization_invitations', 'created_at')
    # ### end Alembic commands ###
