"""add organization member unique constraint

Revision ID: e07e02ce5338
Revises: 47ad7b6204d2
Create Date: 2026-07-22 11:47:14.981117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e07e02ce5338'
down_revision: Union[str, Sequence[str], None] = '47ad7b6204d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_organization_member', 'organization_members', ['organization_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_organization_member', 'organization_members', type_='unique')
    # ### end Alembic commands ###
